### PR TITLE
EL-4011-Tag input add tags on blur

### PR DESCRIPTION
**Pull request by cmallon367**
#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4011

#### Description of Proposed Changes

Updated the documentation to include new input 
Added a karma test 
#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4011-Tag-input-add-tags-on-blur

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4011-Tag-input-add-tags-on-blur~CI/)

### CODE REVIEW

**Review by JonathanToddMF — APPROVED** [review]
Looks good, functionality works as expected

**Comment by JonathanToddMF** [comment]
Plunker here details change - https://plnkr.co/edit/BMcJsHXIcpHEMLf0

Aspects Documentation change here -https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4011-Tag-input-add-tags-on-blur/#/components/input-controls#tags

**Review by donna-marijne — APPROVED** [review]
Looks good, thank you.

**Review by Roland-Penny — APPROVED** [review]
Looks good to me

**Pull request merged**
