### PR TITLE
Build Output Optimization

### PR DESCRIPTION
**Pull request by ashley-hunter**
Removing use of prism loader in some of our sections. While we will likely move back to use this once each category has it's own module, for the time removing these from these sections reduces build output ~1.3mb.

Also remove uglify step from grunt task for Angular 4 library as this is no longer needed - the consuming module loader should take care of this now

### CODE REVIEW

**Comment by ashley-hunter** [comment]
I didn't do this as I haven't removed all occurrences of the use of prism loader. I analysed the webpack bundle and only removed the ones that were having a noticeably negative effect on build output size.

**Comment by ashley-hunter** [comment]
I will look into this to see if disabling on all sections brings much of an further optimization

**Comment by donna-marijne** [comment]
You could see what effect it has on navigation, this is the main reason for precompiling. Since a lot of sections already load asynchronously then it probably won't be much more wonky just to disable it site-wide.

The other option is to fix height on the code sections. Potentially we could do a line count of the snippets during build and generate CSS to fix the height for each.

Funnily enough I noticed that Chrome introduced scroll anchoring recently, which deals with exactly this problem.

**Comment by ashley-hunter** [comment]
Closing, opening another ticket for changes

**Pull request closed without merging**
