### PR TITLE
EL-4093 - Select Repeated Calls

### PR DESCRIPTION
**Pull request by ashley-hunter**
#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4093

#### Description of Proposed Changes

- The issue was actually with the underlying infinite scroll directive that performed a check to see if we are scrolled near the bottom, however when the element is not visible, the height is reported a 0 and the scroll position was also reported as 0, which with our previous calculation assumed we were scrolled to the bottom, in which case we should try and load the next page.
- I have corrected the logic to consider an element with no height (e.g. hidden)
- The ticket suggested creating a select test and performing the set of steps to reproduce the issue (e.g keyboard and mouse presses), but the issue is with the infinite scroll directive and is much easier to reproduce and test directly using it which I have chosen to do instead as this actually tests the underlying issue.

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4093-Select-Repeated-Calls

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4093-Select-Repeated-Calls~CI/)

### CODE REVIEW

**Review by DeanHaire — APPROVED** [review]
Seems to fix the issue for me, code looks fine to me too 👍

**Review by donna-marijne — CHANGES_REQUESTED** [review]
Thank you Ashley, this looks like a good fix that will benefit other components as well. Regarding the e2e test, I think we are missing coverage for keyboard operation of many of our components, so it could be helpful to take this opportunity to implement this issue as a test case since we had planned for it anyway.

**Comment by ashley-hunter** [comment]
Added E2E test which performs selection using keyboard

**Review by DeanHaire — APPROVED** [review]

**Review by donna-marijne — APPROVED** [review]
Looks good, thank you for adding the test!

**Pull request merged**
