### PR TITLE
396581 - Masthead: allow id to be specified for navigation items

### PR DESCRIPTION
**Pull request by JonathanToddMF**
#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://internal.almoctane.com/ui/entity-navigation?p=131002/7002&entityType=work_item&id=396581

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_396581-masthead-ids

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~396581-masthead-ids~CI/)

### CODE REVIEW

**Review by donna-marijne — CHANGES_REQUESTED** [review]
Thanks for this, I think you should update the documentation to include the new interface properties and indicate that they define the HTML `id` attribute.

**Review by donna-marijne — APPROVED** [review]
Verification:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_396581-masthead-ids/#/components/page-header#page-header - :heavy_check_mark:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/caf_CI_ux-aspects-micro-focus_396581-masthead-ids/#/ui-components/layout#masthead - :heavy_check_mark:
https://codesandbox.io/s/masthead-ux-aspects-micro-focus-forked-57qq3f?file=/src/app/app.component.ts - :heavy_check_mark:

**Review by Roland-Penny — CHANGES_REQUESTED** [review]
Looks good - my only tiny nitpick is in the documentation that I think it should be "an HTML ID" rather than "a HTML ID" as the definite article would normally adjust to the spoken form of the word/acronym that follows.

**Review by Roland-Penny — APPROVED** [review]
Looks good

**Review by donna-marijne — APPROVED** [review]

**Pull request merged**
