### PR TITLE
EL-4243 - Remove deprecated features

### PR DESCRIPTION
**Pull request by donna-marijne**
#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4243

#### Description of Proposed Changes

- Remove `valid` input.
- Remove hpe-* icons along with any related styles and documentation.
- Replace `hpe-icon`s with `ux-icon` in the documentation.
- Mark IE11 as deprecated, per [Angular advisory](https://github.com/angular/angular/issues/41840).

I found a bunch of styles from the old AngularJS examples as well, so those have been removed.

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4243-remove-deprecated

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4243-remove-deprecated~CI/)

### CODE REVIEW

**Review by JonathanToddMF — CHANGES_REQUESTED** [review]
Hey Donna, everything here looks in order. However I am noticing the search on the Icon Set page no longer works - https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4243-remove-deprecated/#/css/icons#ux-icons

Apart from that all looks good!

**Comment by donna-marijne** [comment]
Thank you for catching that Jonathan! Should be resolved now.

**Review by JonathanToddMF — APPROVED** [review]
Looks good, QA to follow

**Comment by JonathanToddMF** [comment]
Build appear to be failing but it just looks to be a build error. Running it again to check. Will finalise QA once the build passes

**Comment by donna-marijne** [comment]
Looks like chromedriver is crashing, I don't know why, let me know if you have any ideas.

**Comment by JonathanToddMF** [comment]
Qa complete and verified 
Aspects - https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4243-remove-deprecated/#/landing ✔️
micro focus - https://pages.github.houston.softwaregrp.net/sepg-docs-qa/caf_CI_ux-aspects-micro-focus_EL-4243-remove-deprecated/#/landing ✔️

Awaiting acceptance @ashley-hunter

**Review by ashley-hunter — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
