### PR TITLE
EL-3356 - Marquee wizard templates

### PR DESCRIPTION
**Pull request by ashley-hunter**
Allow a custom template for each marquee wizard step in the side panel.

Ticket
https://autjira.microfocus.com/browse/EL-3356

#### Documentation CI URL
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3356-Marquee-wizard-templates-2

### CODE REVIEW

**Comment by donna-marijne** [comment]
I noticed that Jane requested this, just wanted to check if this change is required in the AngularJS component as well.

**Comment by ashley-hunter** [comment]
Ah, my mistake. I have added a `stepTemplateUrl` to the AngularJS component to allow a custom template provided for it also.

**Comment by ashley-hunter** [comment]
Thanks for the feedback. For the Angular component I have updated the plunker to show it working: https://plnkr.co/edit/MArPA6Bx0WWRkLvCTStw?p=preview

I will make the changes required for the AngularJS component

**Comment by ashley-hunter** [comment]
Made improvements to the AngularJS component to expose those properties. The codepen should now work as expected

**Pull request merged**
