### PR TITLE
MF-Theme-Feedback-09-10 - Updated spacing between buttons

### PR DESCRIPTION
**Pull request by chris-brennan**
- Jira: https://jira.autonomy.com/browse/EL-2821
- Updated buttons to use the same spacing as on EverythingUX, and to use a flex layout to address the additional white space between inline elements.

### CODE REVIEW

**Comment by chris-brennan** [comment]
- Removed styles from documentation stylesheet.
- Added `.btn-container` class to UX Aspects stylesheet and included it in relevant (examples that have more than one button) code snippets, codepen examples, and html files

**Comment by chris-brennan** [comment]
Hi Donna, I don't seem to be able to remove the `.btn-group` class. I think it is needed for positioning the dropdown menu relative to the button. If I replace it with the `btn-container` class, the dropdown will position relative to the container that contains the buttons.

**Comment by donna-marijne** [comment]
Oh, I see. In that case, no changes are needed to this example, so you can revert the addition of .btn-container.

**Comment by chris-brennan** [comment]
OK no probs.  But if I remove the 'btn-container' class then the buttons will display as inline-block and the spacing between each button will contain additional white space.  The 'btn-container' class fixes this by applying a flex layout to it as the parent.  What are your thoughts on this? Thanks

**Comment by donna-marijne** [comment]
No, it's good as it is, I misread the code.

**Comment by chris-brennan** [comment]
ah Ok, No probs at all.

**Comment by chris-brennan** [comment]
yeah sure - I have updated dropdown-ng1 now

**Comment by ashley-hunter** [comment]
Can this be merged, or is it waiting on further changes?

**Pull request merged**
