### PR TITLE
EL-2477

### PR DESCRIPTION
**Pull request by donna-marijne**
Added $navigationMenu and modified minimizeMenu to make use of it.
Added documentation and a CodePen example using $navigationMenu to
control showing/hiding of the nav menu and enabling/disabling auto-hide
behaviour.

https://jira.autonomy.com/browse/EL-2477

### CODE REVIEW

**Comment by ashley-hunter** [comment]
Changes look good, this seems like a much better way of handling things than before. Do you think this would be better documented under the Components page?

**Comment by donna-marijne** [comment]
Yes, I think that would be reasonable. In that case I expect that the whole Side Navigation section should move, since none of that is pure CSS; also, the Page Header > Menu Button section which belongs together with this service.

**Comment by ashley-hunter** [comment]
Yes, I agree, I think that makes much more sense. This feature always did seem a bit out of place on this page to me.

**Comment by donna-marijne** [comment]
Moved relevant sections to Components.

**Pull request merged**
