### PR TITLE
EL-4239 - virtual for selection

### PR DESCRIPTION
**Pull request by donna-marijne**
#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4239

#### Description of Proposed Changes

- uxSelectionItem now handles changes to its data object.
- Range selection was also broken due to the service only having access to the dataset represented by the visible rows, so a `selectionItems` input was added to `uxSelection` to optionally make the full dataset available.
- Documentation for `selectionItems`.
- Test cases for both issues.

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4239-virtual-for-selection

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4239-virtual-for-selection~CI/)

### CODE REVIEW

**Review by ashley-hunter — APPROVED** [review]
Thanks Donna, looks good to me!

**Review by JonathanToddMF — APPROVED** [review]
Looks good, QA to follow

**Comment by JonathanToddMF** [comment]
### QA Complete - two minor issues found.

The following plunker now shows the main issue resolved - https://plnkr.co/edit/470rG7es1Et3BqJN

As you can see selecting the top 11 rows and scrolling no longer "pulls" the selection down with it. Subsequently clicking on a row item responds correctly and highlights the correct row.

## Defect

1. Past row 40 in the list it appears I cannot select multiple rows using a shift + click. Please see the following recording https://gyazo.com/5fa88720ed3c0a6acd91db249210b119
2. It also appears keyboard navigation is effected by this. I don't seem to be able to move up using the keyboard past row 40 in the plunker.

I am unsure if this is expected behaviour or an issue related specifically to my plunker. Any questions feel free to reach out.

Thanks 
-Jonathan

**Comment by donna-marijne** [comment]
Use this code:
https://plnkr.co/edit/4YUFUaPv2Uu4WCIy

You need to use the new input I added, and also remove uxTabbableList since it conflicts.

**Comment by JonathanToddMF** [comment]
## QA Complete

Thank you for the updated plunker Donna. Working as expected now.

I updated my original plunker to now show the main issue resolved - https://plnkr.co/edit/470rG7es1Et3BqJN

As you can see selecting the top 11 rows and scrolling no longer "pulls" the selection down with it. Subsequently clicking on a row item responds correctly and highlights the correct row.
Keyboard navigation and selection works as expected after row 40.

Awaiting acceptance @Roland-Penny 

-Thanks
Jonathan

**Comment by donna-marijne** [comment]
Thanks, sorry, I meant to comment those modifications somewhere but apparently I forgot.

**Review by Roland-Penny — APPROVED** [review]
Looks good - accepted

**Pull request merged**
