### PR TITLE
EL-3626 - Select - valueChanged emitted on initialization

### PR DESCRIPTION
**Pull request by TaraTodd123**
#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licenced under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-3626

#### Description of Proposed Changes

- inputChange and ValueChange no longer being called on initialization for select component
- Tests added for select component for inputChange and ValueChange
- InputChange and tagChange no longer being called on initialization in tags component - needed to be change for multiple select.
- Tests added for tag component for inputChange and tagsChange

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3626-select-valuechange-emitted-on-initialization

### CODE REVIEW

**Comment by TaraTodd123** [comment]
I cannot get the above working with Subject, as I cannot set an initial value to blank/null for the input/value. Also when setting the type of the getter/setters when using Subject there are errors being thrown and I would have to set the type to any.

**Comment by donna-marijne** [comment]
I think the point is that it should not have an initial value. Let me look at the code and get back to you.

**Comment by ashley-hunter** [comment]
Cant this be closed in favour of: https://github.com/UXAspects/UXAspects/pull/1185?

**Comment by TaraTodd123** [comment]
Yes, I'll close it now.

**Pull request closed without merging**
