### PR TITLE
EL-3232 - Dashboard Improvements

### PR DESCRIPTION
**Pull request by ashley-hunter**
Moving offset code to the documentation styles and making grab movement and resizing animated

### CODE REVIEW

**Comment by ashley-hunter** [comment]
No problem, should I keep the animation as it moves and resizes in Grab mode?

**Comment by donna-marijne** [comment]
I also noticed that the dropshadow and a bit of the outline are being clipped in the current build with the offset:
image

**Comment by donna-marijne** [comment]
Yes, the animations looks good, keeping those would be fine I think.

**Comment by ashley-hunter** [comment]
Issues mentioned above should now be fixed. Will raise a quantum ticket to prevent offset in MF

**Comment by ashley-hunter** [comment]
Quantum PR raised: https://github.houston.softwaregrp.net/caf/quantum/pull/582

**Pull request merged**
