### PR TITLE
EL-3372 - Fixing Protractor Tests

### PR DESCRIPTION
**Pull request by ashley-hunter**
Fixing protractor tests. Note I have commented out one dashboard test as this appears to be a bug in the component (however I cannot reproduce it in our docs, showcase page or plunker, only in this test page). I have raised a ticket to correct this: https://autjira.microfocus.com/browse/EL-3381 after which that test can be included again.

#### Ticket
https://autjira.microfocus.com/browse/EL-3372

#### Documentation CI URL
N/A

### CODE REVIEW

**Comment by ashley-hunter** [comment]
It appears there are issues when running the tests on the SEPG machine. From what I understand it is failing because chrome is not installed on the machine so we can't run the tests. Any suggestions?

**Comment by donna-marijne** [comment]
We have our own build image at https://github.com/UXAspects/buildenv-image if anything needs to be added.

**Comment by donna-marijne** [comment]
I'd like to merge this, so could you revert the pom.xml change and we will sort that out in another PR? Thanks.

**Comment by ashley-hunter** [comment]
Done, thanks

**Pull request merged**
