### PR TITLE
EL-3498 - Multiple Select Emit

### PR DESCRIPTION
**Pull request by ashley-hunter**
- Changing Tag Input Component to use Readonly array to ensure setter is called
- Updating component to use a generic instead of `any`.
- Adding a karma test so we can test the actual output event emitter
- Adding some additional teardown logic to existing karma tests

#### Ticket
https://portal.digitalsafe.net/browse/EL-3498

#### Documentation CI URL
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3498-Multiple-Select-Emit

### CODE REVIEW

**Comment by donna-marijne** [comment]
Hi Ashley, you can create a develop-1.7.12 branch off master for PRs for the next release.

**Comment by ashley-hunter** [comment]
Sure will do, thanks

**Comment by donna-marijne** [comment]
If this is ready to review, could you merge develop-1.7.12 into the branch?

**Comment by ashley-hunter** [comment]
Branch has now been updated, thanks

**Pull request merged**
