### PR TITLE
EL-4188 - Select: allow custom debounceTime for filter

### PR DESCRIPTION
**Pull request by DeanHaire**
#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4188

#### Description of Proposed Changes

- Allow customization of debounceTime value for select's filter

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4188-select-filter

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4188-select-filter~CI/)

### CODE REVIEW

**Review by cmallon367 — APPROVED** [review]
Looks good, fix works well & nice use of coerceNumberProperty

**Review by donna-marijne — CHANGES_REQUESTED** [review]
I've set `filterDebounceTime` to 0 and the problem seems to still occur.

https://plnkr.co/edit/NFp4EeBgQrZaCfeF

[Image from Gyazo](https://gyazo.com/0fe76ce20f7dfb5627cb0970130f2f6f)

**Comment by DeanHaire** [comment]
@donna-marijne Christina noticed the same thing, but this is because just typing 'a' will have the United States at the top of the list so this is correct
image
If you type 'al' as the ticket mentions then you'll see the fixed behaviour 😀

**Review by donna-marijne — APPROVED** [review]
I've tried some other combinations and it works fine, so maybe my 'l' key isn't so good. Thanks for the fix!

**Pull request merged**
