### PR TITLE
EL-4227 - menu unexpectedly collapses

### PR DESCRIPTION
**Pull request by cmallon367**
#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4227

#### Description of Proposed Changes

Setting timer is needed to ensure isExpanded$ will not get set to false prematurely due to the debounceTime on the menuShouldClose.
#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4227-menu-unexpectedly-collapses

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4227-menu-unexpectedly-collapses~CI/)

### CODE REVIEW

**Review by JonathanToddMF — APPROVED** [review]
Thanks for this Christina, looks like a nice small change. I can't see anything that stands out. Good work! Functionality works well. 
Here is my plunker for any other reviewers - https://plnkr.co/edit/wNTWI1efmaaDs1WW

**Review by donna-marijne — APPROVED** [review]
I agree, looks like a good fix. Thanks.

**Comment by JonathanToddMF** [comment]
QA across all browsers complete

Following plunker shows that after opening one of the 2nd level submenus the entire menu doesn't collapse.

https://plnkr.co/edit/wNTWI1efmaaDs1WW?preview

**Review by Roland-Penny — APPROVED** [review]
Accepted

**Pull request merged**
