### PR TITLE
EL-4243 - Angular 12

### PR DESCRIPTION
**Pull request by donna-marijne**
#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4243

#### Description of Proposed Changes

- Update dependencies for the docs app and plunker.
- Update peer dependencies for the library.
- Downlevel to typescript 3.9.
- Migrate webpack configs to webpack 5 (required by the new Angular build tools) and updated several loaders/plugins for compatibility.
- `awesome-typescript-loader` doesn't work anymore, so now plunker assets are built and served in parallel with the dev webpack build. This eliminates the need to run the entire docs site with https for the sake of plunker, so the `start:https` task has also been removed.
- Replace `resize-observer-polyfill` because it has not been updated to match the current types.
- Replace several `src` URLs with `require` bindings, since the former no longer work.
- Fixed an issue where the settings in `config.dev.json` were not being provided in the Micro Focus site.
- Update contributing to remove references to `npm run start:https` since this is no longer needed.
- Remove some content under guides which has become inaccurate/outdated.
- Update the ux-aspects-docs package to only include the content under `docs/app/pages/` that the Micro Focus site actually uses. This is primarily to exclude the .module.ts files, which will otherwise cause build errors due to components being declared in more than one module.
- Remove several directives which have been unused for a while.
- Remove shim.js, it has been unused for a while.
- Convert abstract base classes for directives into selectorless directives, this was introduced in Angular 9.
- Fix the `uxTreeGridIndent` to accept `undefined`, resolves an error which occurs when strict compilation settings are enabled.
- Fix some issues with the ngx-mask documentation.

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4243-angular-12

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4243-angular-12~CI/)

### CODE REVIEW

**Review by JonathanToddMF — APPROVED** [review]
Looks good Donna, I can't see anything that stands out to me. QA to follow with Sasi

**Comment by JonathanToddMF** [comment]
Aspects documentation site content verified and working as expected ✔️
MicroFocus documentation site content verified and working as expected ✔️

**Comment by Sdhilipkumar** [comment]
I completed the testing for angular versions 10 and 11, I did not find any issue also there is no console error.

**Comment by JonathanToddMF** [comment]
Awaiting acceptance @Roland-Penny

**Review by Roland-Penny — APPROVED** [review]
Accepted based on dev QA feedback

**Pull request merged**
