### PR TITLE
EL-3619 - Removed documentation-specific styles from e2e test pages

### PR DESCRIPTION
**Pull request by donna-marijne**
#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licenced under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue
https://portal.digitalsafe.net/browse/EL-3619

#### Description of Proposed Changes
The library stylesheet in 2.0 has been stripped of AngularJS and other unnecessary styles, which includes a couple of documentation-specific styles. This will affect the tests that use those styles (`uxd-customize-example` and `uxd-customize-row`), so in preparation for 2.0 I'm aiming to get them removed from our main release. (Mainly it will make merging easier.)

While making these changes, I also changed the select testpage to a column based layout so that it's easier to see the selected options in the screenshot.

Related: https://github.houston.softwaregrp.net/caf/ux-aspects-micro-focus/pull/521

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3619-e2e-documentation-styles

### CODE REVIEW

**Comment by TaraTodd123** [comment]
This looks good, Just one question where you meant to commit the common-icons.ts file? Also, do you want me to take this out of a draft pull request?

**Comment by TaraTodd123** [comment]
Looks like the build has failed on one of the screenshots tests.

**Comment by donna-marijne** [comment]
Thanks for checking, I have reverted the mistaken changes and updated the script so that it generates git compatible line endings in the future.

I don't really know why the test produced that output, it seems to have randomly dropped focus from the select control before capturing the screenshot. A second run was successful.

**Comment by TaraTodd123** [comment]
Thanks, Looks Good!

**Pull request merged**
