### PR TITLE
EL-4233 - 2021 theme updates

### PR DESCRIPTION
**Pull request by donna-marijne**
#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4233

#### Description of Proposed Changes

- ~~Add config for enabling/disabling theme-specific documentation.~~
- Remove forced caps from a documentation example.
- Remove a `!important` rule which prevents theming.

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4233-2021-theme

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4233-2021-theme~CI/)

### CODE REVIEW

**Review by JonathanToddMF — COMMENTED** [review]
Just doubling checking that the Edit in Plunker buttons should be disabled? I couldn't see anything about this in the summary or ticket. Just double checking! 

Otherwise it looks good for approval on this

**Comment by donna-marijne** [comment]
Thank you for checking, no, that was a mistake. I'll try to get that fixed now.

**Review by JonathanToddMF — APPROVED** [review]

**Comment by JonathanToddMF** [comment]
QA Complete, documentation sites checked and components changed in ux-aspects-quantum checked

Aspects - https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4233-2021-theme ✔️ 
Micro Focus - https://pages.github.houston.softwaregrp.net/sepg-docs-qa/caf_CI_ux-aspects-micro-focus_EL-4233-2021-theme ✔️ 

Awaiting Acceptance @ashley-hunter

**Review by ashley-hunter — APPROVED** [review]
Looks good to me, thank you!

**Pull request merged**
