### PR TITLE
EL-4225 - fix error in date & time picker example

### PR DESCRIPTION
**Pull request by donna-marijne**
#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4225

#### Description of Proposed Changes

Due to the `ngSwitch` statement in the template, we can no longer statically bind to the input element inside it.

The error only occurs in the MF site:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/caf_CI_ux-aspects-micro-focus_EL-4225-input-controls-error/#/ui-components/input-controls

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4225-input-controls-error

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4225-input-controls-error~CI/)

### CODE REVIEW

**Review by cmallon367 — APPROVED** [review]
Looks good errors are no longer present!

**Review by JonathanToddMF — APPROVED** [review]
Change works well, error no longer occurring

**Comment by JonathanToddMF** [comment]
QA:
Error not longer appearing in console when navigating to and from the Input Controls section in the documentation site. https://pages.github.houston.softwaregrp.net/sepg-docs-qa/caf_CI_ux-aspects-micro-focus_EL-4225-input-controls-error/#/ui-components/input-controls

Tested on all browsers.

Not sure if this requires a design review. We may be able to merge this straight in. However, awaiting acceptance @Roland-Penny @donna-marijne

**Review by Roland-Penny — APPROVED** [review]
Accepted based on dev QA feedback

**Pull request merged**
