### PR TITLE
EL-4216 - fix popover flickering issue

### PR DESCRIPTION
**Pull request by donna-marijne**
#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4216

#### Description of Proposed Changes

- Revert previous changes due to issue noted above.
- Reduce Keppel arrow size to 8px to match MF theme. Keppel is not used in any supported scenario so this should not cause any problems.
- Add popover screenshot coverage by extending existing fallback e2e tests.

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4216-popover-2

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4216-popover-2~CI/)

### CODE REVIEW

**Comment by cmallon367** [comment]
Chrome

**Comment by donna-marijne** [comment]
I've tried it in all browsers and can't reproduce.
https://gyazo.com/7d6eb8a1f0fee2e47b544bb5d97c789b

Can you investigate on your environment please?

**Comment by cmallon367** [comment]
Yes sure no problem

**Review by JonathanToddMF — APPROVED** [review]
Can't see any issues with this, flickering issue resolved. Regressions from https://github.com/UXAspects/UXAspects/pull/1486 removed

**Review by cmallon367 — APPROVED** [review]
Fix works well and issue was not reproducible at 100% in any of our supported browsers

**Pull request merged**
