### PR TITLE
EL-4186: ux-combobox not closing when readonlyInput property set to true

### PR DESCRIPTION
**Pull request by JonathanToddMF**
Contains fix. Tests coverage incoming.

#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue
https://portal.digitalsafe.net/browse/EL-4186

#### Description of Proposed Changes
1. added call to focus on #singleInput when the ux-select-icon is clicked.
2. Test coverage

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4186-combobox-readonlyinput

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/view/Developer/job/caf~ux-aspects-micro-focus~EL-4186-combobox-readonlyinput~CI/)

### CODE REVIEW

**Review by cmallon367 — APPROVED** [review]
Looks good!

**Review by donna-marijne — APPROVED** [review]
Looks good, thank you.

**Comment by cmallon367** [comment]
QA of ux-combobox
Tested in all supported browsers, an no console log errors working as expected
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4186-combobox-readonlyinput/#/components/select#select 
Issue: 
When using ux-combobox and ux-dropdown with readonlyInput set to true. Under those conditions, if you click on the arrow icon (not the main dropdown body) to open the dropdown, the dropdown can only be closed by clicking the dropdown body or arrow icon again. Without readonlyInputset, the dropdown can be closed by clicking anywhere outside the dropdown.
Plunker showing the issue: 
https://plnkr.co/edit/EcbjUcRJW0soHs7m - uxaspects 
https://plnkr.co/edit/TXELJTg4bHDECHgt- Microfocus 
Fix: 
The fix was to make sure the focus is being triggered whenever the button has been clicked by adding a call to focus on #singleInput when the ux-select-icon is clicked. Now if you re-do the steps outlined above you will see that the dropdown can be closed by clicking the arrow, pressing on the main body and also from clicks outside the dropdown and also a focus element can be seen around the input field whenever the icon is clicked. 
https://plnkr.co/edit/6qawKAuElpOAZfeB - microfocus 
https://plnkr.co/edit/SO71EgJgnxGv60jV - uxaspects

**Review by Roland-Penny — APPROVED** [review]
Accepted

**Pull request merged**
