### PR TITLE
El 3372 fixing protractor tests

### PR DESCRIPTION
**Pull request by ashley-hunter**
Fixing Protractor Issues:
- Added missing hasIndicator property
- Fixing hierarchy bar selector
- Fixing select tests as multiple selects no longer close the dropdown on selection
- Fixing tab test which was just wrong

#### Ticket
https://autjira.microfocus.com/browse/EL-3372

#### Documentation CI URL
N/A

### CODE REVIEW

**Comment by ashley-hunter** [comment]
Hmm, I'm not able to reproduce this failure. Was the Angular library rebuilt before running the tests? 1999 was the value it should have been before we added the 10 item buffer in this sprint.

If not then will probably have to raise a new ticket as I am unable to reproduce this.

**Comment by donna-marijne** [comment]
Yes, it was rebuilt. It has the look of a timing-dependent issue to me.

**Comment by ashley-hunter** [comment]
Ok, no problem, I will raise another ticket. Thanks

**Comment by donna-marijne** [comment]
Great. Could you comment/remove the failing test in the meantime?

**Comment by ashley-hunter** [comment]
Thats it commented out for now, thanks

**Pull request merged**
