### PR TITLE
374514 - Side Panel - Prevent scrolling of content behind side panel

### PR DESCRIPTION
**Pull request by JonathanToddMF**
#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://internal.almoctane.com/ui/entity-navigation?p=131002/7002&entityType=work_item&id=374514

#### Description of Proposed Changes

- Added preventBackgroundScroll input that prevents the scrolling of background content. This adds the `.modal-open` class to the body or container. 
- Updated documentation site and snippet with new input
- Updated E2E test to cover new functionality
- Reporter happy to live with focus issue mentioned in original request

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_374514-side-panel-scroll

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~374514-side-panel-scroll~CI/)

### CODE REVIEW

**Review by donna-marijne — CHANGES_REQUESTED** [review]
Hi, I think there was a misunderstanding. The non-modal side panel must allow interaction with the main content while the side panel is open. This option disables the ability to scroll the main content, even if focus in within the main content.

**Comment by JonathanToddMF** [comment]
Understood, I can make the change to that. 

Should I remove the input for this and make it the default behaviour? Or keep it as is as a opt in feature.

**Comment by donna-marijne** [comment]
If you can find a fix without any negative impact, certainly it doesn't need a configuration option. You might be able to stop propagation of the wheel event within the side panel.

**Comment by JonathanToddMF** [comment]
Hi @donna-marijne, I spent some time playing around with preventing the scrolling with JS but it would often be quite glitchy and allow some minor scrolling before being locked in place, it didn't perform adequately. Also in container mode it would require the user to specify which element they would like to disable scrolling as it isn't always the parent element. 

I kept it as a class that is applied, and also kept it as I configuration option, as it requires additional CSS for the use in the container mode which I detailed more in the Input in the docs.

**Comment by donna-marijne** [comment]
I did some research and there's a CSS property `overscroll-behavior` which seems to exist for this exact purpose. Give it a try.

https://plnkr.co/edit/hb8aHBBUmyQekUqu

**Pull request merged**
