### PR TITLE
EL-4231 - Dashboard doesn't move back when resize is cancelled

### PR DESCRIPTION
**Pull request by cmallon367**
#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4231

#### Description of Proposed Changes

Added an extra check on the shiftWidgetsUp function 

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4231-Dashboard-widget-does-not-move-back

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4231-Dashboard-widget-does-not-move-back~CI/)

### CODE REVIEW

**Review by JonathanToddMF — DISMISSED** [review]
Change works well. Thank Christina

**Review by donna-marijne — CHANGES_REQUESTED** [review]
Actually I think you might not even need a new function. Can you try something like this?
```
                const isPreviousPositionAvailable = this.getPositionAvailable(
                    cachedVersionOfWidget.column, 
                    cachedVersionOfWidget.row, 
                    cachedVersionOfWidget.columnSpan, 
                    cachedVersionOfWidget.rowSpan, 
                    widget
                );
                if (isPreviousPositionAvailable && widget.row !== cachedVersionOfWidget.row) {
                    widget.setRow(cachedVersionOfWidget.row);
                    stable = false;
                }
```

Using the 5th argument means that it doesn't check that the 1x2 widget collides with itself.

**Comment by cmallon367** [comment]
@donna-marijne your right that did work & its a lot less code, thanks

**Review by donna-marijne — APPROVED** [review]

**Review by JonathanToddMF — APPROVED** [review]
Works well!, QA to follow

**Comment by JonathanToddMF** [comment]
## QA

Issue resolved in the following plunker - https://plnkr.co/edit/nZEeKpfcXjGszEEL
Dragging the service status widget to push a widget down and then moving it back causes the Users widget to shift back up into its previous position.

Tested and working on all browsers

**Review by Roland-Penny — APPROVED** [review]
Accepted

**Pull request merged**
