### PR TITLE
EL-4219 - Node 12 build image

### PR DESCRIPTION
**Pull request by donna-marijne**
#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4219

#### Description of Proposed Changes

- Update the build image to 2.0.0 (Node 12).
- Add `generate:iconset` script. The webfont setup doesn't work with Node 12, and I haven't had any luck updating it without corrupting the icons, so this is a command which will run `grunt iconset` in the Node 10 version of our docker container.
- Update documentation that refers to Node 10.
- Fix some issues with running e2e locally.

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4219-node-12

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4219-node-12~CI/)

### CODE REVIEW

**Review by JonathanToddMF — APPROVED** [review]
Looks good, took the time to install nvm to make testing this easier.

**Comment by donna-marijne** [comment]
You need to assign Roland for review.

**Comment by JonathanToddMF** [comment]
QA Complete 
Documentation site build link - https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4219-node-12

**Review by Roland-Penny — APPROVED** [review]
Accepted based on dev QA feedback

**Pull request merged**
