### PR TITLE
EL-4140 - Add alert link styling

### PR DESCRIPTION
**Pull request by cmallon367**
#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4140

#### Description of Proposed Changes

Add alert link styles
Updated the documentation example to include hyperlinks

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4140-Alert-link-styling

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4140-Alert-link-styling~CI/)

### CODE REVIEW

**Comment by cmallon367** [comment]
Plunker showing alert variants with hyperlinks. https://plnkr.co/edit/eWJ6b7QBUDbUiSpO

**Comment by cmallon367** [comment]
Microfocus plunker showing all alert variants with hyperlinks https://plnkr.co/edit/btwPdnwX7dfx8G4S

**Review by JonathanToddMF — DISMISSED** [review]
Looks good christina

**Review by JonathanToddMF — APPROVED** [review]

**Comment by JonathanToddMF** [comment]
QA Complete

Plunker showing alert variants with hyperlinks. https://plnkr.co/edit/eWJ6b7QBUDbUiSpO
Microfocus plunker showing all alert variants with hyperlinks https://plnkr.co/edit/btwPdnwX7dfx8G4S

Awaiting acceptance @Roland-Penny

**Review by Roland-Penny — CHANGES_REQUESTED** [review]
The link styling that has been added looks fine for the normal state but I notice that on hover the link underline disappears rather than using the opacity change on the link/text and underline as per Carsten's original request & url that are on EL-4140

**Comment by donna-marijne** [comment]
Yes, I'll remove the hover styling. We cannot make an opacity change since it will affect contrast, and there are already contrast issues with this design.

**Comment by Roland-Penny** [comment]
@donna-marijne  Thanks - that's fine

**Pull request merged**
