### PR TITLE
EL-3468 - Side Panel focus

### PR DESCRIPTION
**Pull request by donna-marijne**
* Using Angular animations in order to set `visibility` with the proper timing. `visibility: hidden` prevents focus landing on panel content when it is closed.
* Converted the duration and timing function to match quantum.

#### Ticket
https://portal.digitalsafe.net/browse/EL-3468

#### Documentation CI URL
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3468-side-panel

### CODE REVIEW

**Comment by ashley-hunter** [comment]
There appears to be Side Panel tests failing at the moment?

**Comment by donna-marijne** [comment]
There's an error on the e2e site. Is there some extra dependency required for loading a component with animations?

**Comment by ashley-hunter** [comment]
Ah, BrowserAnimationsModule will need imported in AppModule

**Comment by ashley-hunter** [comment]
Hmm, actually it looks like it is already there, I will take a look into it now

**Comment by donna-marijne** [comment]
It might be the enum, I just found this: https://github.com/angular/angular/issues/24047

**Comment by ashley-hunter** [comment]
I see someone mentions there to add `export` to the enum and it should work?

**Comment by ashley-hunter** [comment]
Yeah, adding `export` seems to fix it for me

**Comment by donna-marijne** [comment]
For some reasons the animations don't apply to the subclass component ux-item-display-panel, could you take a look and let me know if you can see what's missing?

**Comment by ashley-hunter** [comment]
Sure no problem

**Comment by ashley-hunter** [comment]
That should be it fixed, the `ItemDisplayPanelComponent` class had an `ngOnInit` function so the `ngOnInit` in the `SidePanelComponent` was never getting called which is where the animation state changes were setup.

**Comment by donna-marijne** [comment]
Great catch, thank you very much!

**Comment by donna-marijne** [comment]
Should be good for review again now.

**Pull request merged**
