### PR TITLE
EL-3666 - Added padding to prevent overlap with icons

### PR DESCRIPTION
**Pull request by donna-marijne**
#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licenced under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue
https://portal.digitalsafe.net/browse/EL-3666

#### Description of Proposed Changes
Added right padding to allow for the chevron, and dynamic additional padding when the clear button is present.

Added screenshot verification of overflow appearance, and also a new test case for the clear button.

Also consolidated two test cases with very similar functionality.

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3666-select-overlap

### CODE REVIEW

**Comment by donna-marijne** [comment]
Isn't this a pre-existing issue?

**Comment by ashley-hunter** [comment]
Yes, I wasn't sure if it should be address this as part of this ticket or not. If not, then I'm happy to approve this PR as is, it all seems to be working well.

**Comment by donna-marijne** [comment]
I think it would be worth raising a ticket for it. From my understanding the urgent complaint here was the text overlapping with the button(s).

**Comment by donna-marijne** [comment]
Thanks Ashley.

**Pull request merged**
