### PR TITLE
EL-4262 - Multiple Select: input field unnecessarily wraps to the next line

### PR DESCRIPTION
**Pull request by JonathanToddMF**
#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-4262

#### Description of Proposed Changes

Added flex and min-width to tag-input.component.less

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-4262-multiple-select-wrap

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-4262-multiple-select-wrap~CI/)

### CODE REVIEW

**Review by donna-marijne — APPROVED** [review]
Verification:

Select:
https://plnkr.co/edit/N9iU23lhgMIINNAo (open source) - :heavy_check_mark:
https://plnkr.co/edit/NeKPBBAWbHa7ARC7 (Micro Focus) - :heavy_check_mark:

Tag Input:
https://plnkr.co/edit/IXSLrfnq0ZHtW3HR (open source) - :heavy_check_mark:
https://plnkr.co/edit/CA7JStBJDVameXhR (Micro Focus) - :heavy_check_mark:

**Review by Roland-Penny — COMMENTED** [review]
@JonathanToddMF - I don't quite understand the behaviour here. On these tests, if I have shorter placeholder text, it seems to wrap when there should be enough space for the placeholder text next to the last tag/pill. Am I missing something?

image

**Comment by JonathanToddMF** [comment]
> @JonathanToddMF - I don't quite understand the behaviour here. On these tests, if I have shorter placeholder text, it seems to wrap when there should be enough space for the placeholder text next to the last tag/pill. Am I missing something?
> 
> image

HI Roland,

Thanks for your message. There is a min-width of 140 pixels as a default for all placeholder text. Without the min-width the text will overflow outside of the input, like so:
image

**Comment by Roland-Penny** [comment]
@JonathanToddMF Thanks Jonathan. That explains it. So I guess the min width setting would need to get customized for the length of a particular placeholder text string if space usage was very important.

**Comment by donna-marijne** [comment]
Is anything else needed here, or shall I merge?

**Comment by JonathanToddMF** [comment]
> Is anything else needed here, or shall I merge?

The customisable min-width that Roland mentioned may need addressed from a design perspective. However, if that is a separate issue to this or an additional change on top of this I am unsure. 

What are your thoughts @donna-marijne?
Maybe an input on the component to provide a min-width?

**Comment by donna-marijne** [comment]
I think this resolves the request, the min-width is naturally customizable via CSS.

**Comment by JonathanToddMF** [comment]
Good point, an input would needlessly complicate it.

On that, this is good to merge.

**Review by Roland-Penny — APPROVED** [review]
That's fine

**Pull request merged**
