### PR TITLE
angular tree component for docs

### PR DESCRIPTION
**Pull request by TaraTodd123**
#### Checklist
* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

Error when navigating to the tree-view component in IE release build

#### Description of Proposed Changes

As per https://github.com/UXAspects/UXAspects-2/pull/21, this fixed the issue in the UXAspects-2 and ux-aspects-micro-focus-2 repos

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_angular-tree-for-docs-fix

#### Downstream Build(s)

https://jenkins.swinfra.net/job/SEPG/job/caf/view/Developer/job/caf~ux-aspects-micro-focus~angular-tree-for-docs-fix~CI/

### CODE REVIEW

**Comment by TaraTodd123** [comment]
The builds seems to be failing but I don't believe its to do with this fix https://jenkins.swinfra.net/job/SEPG/job/UXAspects/view/Developer/job/UXAspects~UXAspects~angular-tree-for-docs-fix~CI/2/console

**Comment by donna-marijne** [comment]
Is this the URL that had problems?

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/caf_CI_ux-aspects-micro-focus_develop-1.8.13/#/ui-components/tables#tree-view

**Comment by TaraTodd123** [comment]
Yes, on IE11 it wont open the page.

**Comment by donna-marijne** [comment]
Yes, I see. Looks like that was the case in our current release as well.

**Comment by TaraTodd123** [comment]
Yes, the UXAspects-2 repos and ux-aspects-micro-fcous-2 repos seems to be working fine now will this fix so hopefully it does work. Though the builds are failing now so I cant even see.

**Comment by donna-marijne** [comment]
Yeah, it's a compile error. I'll push a fix in a moment.

**Comment by donna-marijne** [comment]
Let's merge this after the release to avoid making another 45 min build.

**Pull request merged**
