### PR TITLE
EL-3781 - Cypress

### PR DESCRIPTION
**Pull request by ashley-hunter**
#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-3781

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects_EL-3781-Cypress

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus~EL-3781-Cypress~CI/)

### CODE REVIEW

**Comment by ashley-hunter** [comment]
@donna-marijne Looks like we are still encountering the same linux/windows font rendering issues as with protractor: 
image

**Comment by donna-marijne** [comment]
I thought Tara had this working last year?

**Comment by pamadei-mf** [comment]
I will have a look at Tara's work.

**Comment by ashley-hunter** [comment]
Thank you Pablo!

**Comment by donna-marijne** [comment]
Thanks, I believe this was the branch: https://github.houston.softwaregrp.net/caf/ux-aspects-micro-focus-seed/tree/EL-3741-cypress-screenshot-testing

**Comment by ashley-hunter** [comment]
Hmm, I'm getting the font differences in Tara's branch too

**Comment by pamadei-mf** [comment]
Yes, I just started the docker image in Tara's branch and some tests are failing.

**Comment by ashley-hunter** [comment]
So running in the docker image should be more reliable with screenshots in terms of font rendering, but running on windows is showing screenshot failures for me

**Comment by donna-marijne** [comment]
Tara's comment here indicates that she was able to run the test in both environments using the same screenshot reference: https://portal.digitalsafe.net/browse/EL-3741?focusedCommentId=2524586&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2524586

@TaraTodd123 if you get a moment could you confirm whether you can still reproduce the above results on your dev environment?

**Comment by pamadei-mf** [comment]
Noticed that the Electron version in my dev environment is different than that the one Tara used for this investigation (unsure if this could have an effect on the results).
Annotation 2020-04-02 135438

**Comment by TaraTodd123** [comment]
Sorry, my docker is being extremely slow at the moment. Yes, when I done this last year I was able to run it locally and then on the docker image and the screenshots matched and there was no issues with fonts. As Pablo mentioned above I was using Electron 87 and it seems that the default one now showing is Electron 73 locally. Hopefully this quickens up and I can get back to you and let you know.

**Comment by TaraTodd123** [comment]
Sorry I don't know why it was running so slow. I am getting the same results as Pablo and Ashley the fonts are causing differences in the screenshots on my docker environment but as Pablo as mentioned it is Electron version that seems to be running. Sorry.

**Comment by donna-marijne** [comment]
No problem, thank you for jumping in to check that for us.

**Comment by pamadei-mf** [comment]
Thank you @TaraTodd123.

Yesterday and today, I tried a few more things in Tara's branch and these were the findings.

Cypress version: 4.3.0 (latest version)
Electron 80

- When taking the screenshots in Windows and running cypress again. All tests passed.

- When taking the screenshots in Windows (with “Run All Test” button) and running cypress again. 4 screenshot tests failed but after running it a couple of times. “Run All Test” Button is less consistent as Tara mentioned in her ticket.

- When taking the screenshots in Windows and running cypress in the Docker container. All the screenshots tests failed due to fonts. I believe this is the same behaviour in Protractor.

- When taking the screenshots in the Docker container and running Cypress again. All tests passed. Although, 3 tests are not running due to a Possible EventEmitter memory leak detected. **Investigating**.

- When taking the screenshots in the Docker container and running Cypress in Windows. All screenshot tests failed due to fonts.

**Comment by donna-marijne** [comment]
Here's a few ideas to try, if you haven't already:
* Firefox instead of chrome.
* [Tweak the thresholds.](https://www.npmjs.com/package/cypress-image-snapshot#options)
* Reduce the scope of the screenshots (e.g. don't capture the "meta" controls)

If none of that works, we'll probably need to rethink this.

**Comment by pamadei-mf** [comment]
- Firefox instead of chrome.
Screenshots still failed running cypress in the Docker Image.

- Tweak the thresholds.
While this is a feasible solution tweaking the failure threshold can bring issues in the future. Real differences could be as low as 0.15% which it will make it really hard to set a threshold. A higher threshold will eliminate the cross platform font rendering failures. However, we are risking to not see small and real differences.

- Reduce the scope of the screenshots (e.g. don't capture the "meta" controls).
Reducing the scope of the screenshots by not capturing the meta controls is another possible solution. Although this setup is straightforward (at the moment I was not able to modify the select test correctly to only capture the dropdown and selectedLocation). Every test will need to be tweaked and this doesn't guarantee that we won’t have font rendering issues.

Another solution could be to use a Cypress docker image to run the tests. I will look at this possible solution.

**Comment by pamadei-mf** [comment]
I was able to run the tests located in my local env using the Cypress Docker Image. With this approach there is no need of `npm install or builds` in the Docker Image. Cypress is already installed in the container so after the container is up the only command needed is `npm run test:cypress` (which will run Electron headless). Definitely an improvement. Much faster than the current `npm run docker:ci` command. Screenshots can be taken in the Cypress Docker Image and saved in the local repo. 
I will check that the Jenkins build runs and we are not getting any issues with the screenshots.

**Comment by donna-marijne** [comment]
@andyreidz FYI

**Comment by donna-marijne** [comment]
Do either of you mind if I close this PR? I will leave the remote branch in place for future use.

**Comment by ashley-hunter** [comment]
Fine by me!

**Comment by donna-marijne** [comment]
Closing since Cypress will not solve our immediate need, this will be done later in the year.

**Pull request closed without merging**
